# Auto-generated by Coordinate Tool
#
# WARNING: Any changes to this file will be overwritten.

from core.models.Coordinates import Coordinates
from core.models.ColorCoordinates import ColorCoordinates

COORDINATES_AUTO_GENERATED = {
    "quest": Coordinates(40, 28),
    "menu_settings": Coordinates(669, 40),
    "heroic": Coordinates(553, 239),
    "hard": Coordinates(360, 242),
    "normal": Coordinates(166, 240),
    "auto_team": Coordinates(202, 471),
    "accept_team": Coordinates(482, 465),
    "auto_pilot": Coordinates(697, 263),
    "persuasion_top_left": Coordinates(53, 45),
    "persuasion_bottom_right": Coordinates(655, 183),
    "decline_familiar": Coordinates(265, 452),
    "accept_familiar": Coordinates(158, 344),
    "confirm_familiar": Coordinates(287, 360),
    "bribe_familiar": Coordinates(555, 343),
    "fishing": Coordinates(676, 417),
    "fish_play": Coordinates(280, 323),
    "fish_start": Coordinates(358, 484),
    "fish_cast": Coordinates(357, 488),
    "fish_catch": Coordinates(357, 488),
    "is_trash": ColorCoordinates(436, 443, 181, 222, 71),
    "fish_minimum_range": ColorCoordinates(129, 405, 14, 14, 15),
    "fish_max_catch_rate": ColorCoordinates(648, 402, 78, 255, 0),
    "is_fishing_state": ColorCoordinates(414, 22, 37, 31, 23),
    "select_worm": Coordinates(431, 404),
    "worm_box_1": Coordinates(209, 216),
    "worm_box_2": Coordinates(282, 215),
    "worm_box_3": Coordinates(355, 216),
    "worm_box_4": ColorCoordinates(353, 220, 128, 252, 145),
    "dungeon": {
        "1": {
            "1": Coordinates(197, 338),
            "2": Coordinates(538, 191),
            "3": Coordinates(618, 325),
            "4": Coordinates(363, 237),
        },
        "2": {
            "1": Coordinates(475, 389),
            "2": Coordinates(505, 156),
            "3": Coordinates(165, 278),
            "4": Coordinates(362, 266),
        },
        "3": {
            "1": Coordinates(526, 391),
            "2": Coordinates(381, 311),
            "3": Coordinates(101, 191),
            "4": Coordinates(524, 174),
        },
        "4": {
            "1": Coordinates(251, 409),
            "2": Coordinates(218, 198),
            "3": Coordinates(615, 206),
            "4": Coordinates(354, 286),
        },
        "5": {
            "1": Coordinates(99, 210),
            "2": Coordinates(354, 405),
            "3": Coordinates(598, 247),
            "4": Coordinates(512, 155),
        },
        "6": {
            "1": Coordinates(106, 278),
            "2": Coordinates(485, 415),
            "3": Coordinates(478, 173),
            "4": Coordinates(334, 271),
        },
    },
    "return_home": Coordinates(447, 480),
    "is_home_state": ColorCoordinates(690, 118, 146, 20, 20),
    "is_auto_pilot_disabled": ColorCoordinates(688, 260, 214, 38, 30),
    "is_disconnected": ColorCoordinates(361, 349, 47, 175, 209),
    "worm_bar_box": Coordinates(456, 404),
    "rerun_dungeon": Coordinates(298, 477),
    "persuasion_has_succeeded": ColorCoordinates(405, 462, 57, 180, 211),
}
