from core.ExecutableUtilities import ExecutableUtilities

# =======================
# SCALE FACTOR
# =======================
SCALE = 1.5

# =======================
# PATHS 
# =======================
IMAGES_PATH = ExecutableUtilities.resource_path("data\images")
CONSTANTS_PATH = ExecutableUtilities.resource_path("core\constants")

APPLICATION_ICON = rf"{IMAGES_PATH}\window_icon.ico"
DUNGEON_PATH = rf"{IMAGES_PATH}\dungeon.png"
FAMILIAR_ENCOUNTERED_PATH = rf"{IMAGES_PATH}\familiar_encountered.png"
ON_BUTTON_PATH = rf"{IMAGES_PATH}\on.png"
OFF_BUTTON_PATH = rf"{IMAGES_PATH}\off.png"
ON_DARK_BUTTON_PATH = rf"{IMAGES_PATH}\on_dark.png"
OFF_DARK_BUTTON_PATH = rf"{IMAGES_PATH}\off_dark.png"
FISH_PATH = rf"{IMAGES_PATH}\fish.png"
AUTO_QUEST_ICON_PATH = rf"{IMAGES_PATH}\auto_quest_icon.png"
AUTO_FISH_ICON_PATH = rf"{IMAGES_PATH}\auto_fish_icon.png"
GENERAL_SETTINGS_ICON_PATH = rf"{IMAGES_PATH}\general_settings_icon.png"
COORDINATES_ICON_PATH = rf"{IMAGES_PATH}\coordinate_icon.ico"
GAME_PATH_ICON = rf"{IMAGES_PATH}\game_path_icon.png"
INFO_PATH_ICON = rf"{IMAGES_PATH}\info_icon.png"
DISCORD_ICON_PATH = rf"{IMAGES_PATH}\discord_icon.png"
GITHUB_ICON_PATH = rf"{IMAGES_PATH}\github_icon.png"
WIKI_ICON_PATH =  rf"{IMAGES_PATH}\wiki_icon.png"
COORDINATE_AUTOGENERATED_FILE = f"{CONSTANTS_PATH}\GeneratedCoordinates.py"

# =======================
# FONTS 
# =======================
GLOBAL_FONT = "Edit Undo BRK"

AUTO_FRAME_HEADER_FONT = (GLOBAL_FONT, int(26 * SCALE))  # 39
AUTO_FRAME_CONTENT_TITLE_FONT = (GLOBAL_FONT, int(14 * SCALE))  # 21
AUTO_FRAME_CONTENT_FONT = (GLOBAL_FONT, int(10 * SCALE))  # 15
STAT_FRAME_FONT = (GLOBAL_FONT, int(56 * SCALE))  # 84
LOG_FONT = ("Pixel Digivolve", int(12))  # 18
COORDINATE_TOOL_FONT = ("Arial", int(9 * SCALE))  # 18
COORDINATE_TOOL_SMALL_FONT = ("Arial Bold", int(7 * SCALE))  # 18
GAME_PATH_FONT = (GLOBAL_FONT, 10)
DISCLAIMER_FONT = (GLOBAL_FONT, 9)

# =======================
# TEXTS 
# =======================
APPLICATION_NAME = "Bot Heroes"
AUTO_QUEST_DIFFICULTY = ["NORMAL", "HARD", "HEROIC"]
APPEARANCE_MODE = ["Use system settings", "Dark", "Light"]
APPEARANCE_MODE_TITLE = "APPEARANCE MODE:"
AUTO_QUEST_TITLE = "AUTO QUEST"
AUTO_FISH_TITLE = "AUTO FISH"
GENERAL_SETTINGS_TITLE = "GENERAL SETTINGS"
COORDINATE_TOOL_NAME= "Coordinate Tool"
GAME_PATH_LABEL_TITLE = "GAME PATH"
GAME_PATH_DEFAULT_TEXT = "NO GAME PATH SELECTED"
INFO_TITLE = "INFO"
INFO_LABEL_TITLE = "⚠️ Disclaimer"
INFO_LABEL_DISCLAIMER = """This tool is created strictly for educational and research purposes. It is not intended for use with live game accounts or for violating any game's Terms of Service. Using automation tools in online games may lead to account bans or other penalties. The author is not responsible for any misuse of this code."""
ZONE_FIRST_OPTION = "SELECT ZONE"
DUNGEON_FIRST_OPTION = "SELECT DUNGEON"

# =======================
# SIZE AND POSITION 
# =======================
WINDOW_SIZE = (1582, 615)

# Don't ask me how I found these numbers, but they work perfectly 
BIT_HEROES_SIZE = (int(720 ), int(537 ))  
BIT_HEROES_SIZE_2 = (int(721 ), int(538 ))  
RECTANGLE_MASK = (int(717), int(536 )) 

GAME_FRAME_SIZE = (int(490 * SCALE), int(375 * SCALE))  # (735, 562)
GAME_FRAME_INTERNAL_PADDING = int(6 * SCALE)  # 9

FRAME_CORNER_RADIUS = int(20 * SCALE)  # 30
CONTAINER_FRAME_SIZE = (int(865 * SCALE), GAME_FRAME_SIZE[1])  # (1297, 562)
CONTAINER_FRAME_RADIUS = 30 
GAME_FRAME_PADDING = int(20 * SCALE)  # 30
STAT_FRAME_SIZE = (int(160 * SCALE), int(75 * SCALE))  # (240, 112)
STAT_FRAME_PADDING = int(11 * SCALE)  # 16
AUTO_FRAME_SIZE = (int(250 * SCALE), int(175 * SCALE))  # (375, 262)
AUTO_FRAME_PADDING = int(5 * SCALE)  # 7
AUTO_FRAME_CORNER_RADIUS = int(15 * SCALE)  # 22
AUTO_FRAME_MENU_SIZE = (int(100 * SCALE), int(25 * SCALE))  # (165, 37)
AUTO_FRAME_HEIGHT = int(105 * SCALE)  # 142
ROW_FRAME_WIDTH = int(505 * SCALE)  # 757

LOG_CORNER_RADIUS = int(15 * SCALE)  # 22
LOG_SIZE = (int(340 * SCALE), int(150 * SCALE))  # (510, 225)
LOG_PADDING = int(5 * SCALE)  # 7
INTERNAL_PADDING = int(7 * SCALE)  # 10
BUTTON_SELECT_BAR_WIDTH = int(355 * SCALE)  # 532
BUTTON_SELECT_BAR_HEIGHT = int(100 * SCALE)  # 150
BUTTON_WIDTH = int(45 * SCALE)  # 67
BUTTON_HEIGHT = int(25 * SCALE)  # 37
BUTTON_CORNER_RADIUS = int(70 * SCALE)  # 105
BUTTON_PADDING = int(3 * SCALE)  # 4
SELECT_BAR_PADDING = int(5 * SCALE)  # 7
SELECT_BAR_CORNER_RADIUS = int(15 * SCALE)  # 22
FAMILIAR_LISTBOX_WIDTH = int(75 * SCALE)  # 225

WINDOWS_TOP_BAR_HEIGHT = int(35)
WINDOWS_LEFT_BAR_WIDTH = int(10) 

# Images
DUNGEON_SIZE = (int(52 * SCALE), int(67 * SCALE))  # (78, 100)
FAMILIAR_ENCOUNTERED_SIZE = FISH_SIZE = (int(59 * SCALE), int(59 * SCALE))  # (88, 88)
ON_OFF_SIZE = (int(125 * SCALE), int(92.5 * SCALE))  # (187, 138)
ON_BUTTON_PADDING = int(5 * SCALE)  # 7
BUTTON_SELECT_ICON_SIZE = (30, 30) 
DISCORD_ICON_SIZE = (177/4, 152/4)
GITHUB_ICON_SIZE = (428/11,428/11)
WIKI_ICON_SIZE = (121/4,143/4)

GAME_PATH_CONTAINER_CORNER_RADIUS = 10
GAME_PATH_CONTAINER_WIDTH = 350
GAME_PATH_CONTAINER_HEIGHT = 40


# =======================
# COLORS
# =======================

RARITY_COLORS = {
    "common": "#32CD32",    # Lime Green
    "rare": "#5FD2F8",      # Dodger Blue
    "epic": "#BA55D3",      # Medium Orchid
    "legendary": "#FF8C00"  # Dark Orange
}

GAME_PATH_CONTAINER_DARK_COLOR = "#282828"
GAME_PATH_CONTAINER_LIGHT_COLOR = "#bebebe"

SELECT_BAR_DARK_COLOR = "#282828"
SELECT_BAR_LIGHT_COLOR = "#bebebe"

ERROR_COLOR = "red" 

# =======================
# TOOLTIPS
# =======================
TOOLTIP_FONT = (GLOBAL_FONT, int(10 * SCALE))  # 15
TOOLTIP_WRAPLENGTH = int(120 * SCALE)  # 180
TOOLTIP_DELAY = 0.2
TOOLTIP_PARAMETERS = {"font": TOOLTIP_FONT, "wraplength": TOOLTIP_WRAPLENGTH, "delay": TOOLTIP_DELAY}

# AutoQuest
AUTO_QUEST_ICON_TOOLTIP = "Open Auto Quest Configuration"
ZONE_TOOLTIP = "Choose the zone for automatic questing."
DUNGEON_TOOLTIP = "Choose the dungeon for automatic questing."
PERSUADE_TOOLTIP = "Enable to automatically persuade familiars selected in the familiar table by using coins."
DECLINE_TOOLTIP = "Enable to automatically decline familiars that are not selected in the familiar table"
FAMILIAR_TOOLTIP = "Select one or more familiars to catch automatically. This feature works only when auto persuade is enabled."

# AutoFish
AUTO_FISH_ICON_TOOLTIP = "Open Auto Fish Configuration"

# General settings
GENERAL_SETTINGS_TOOLTIP = "Open General Settings"
APPEARANCE_MODE_TOOLTIP = "Select the appearance mode to customize the application's visual theme."
INFO_TOOLTIP = "Open Info Page"

# Stats
DUNGEON_STAT_TOOLTIP = "Total number of dungeons completed."
FAMILIAR_STAT_TOOLTIP = "Number of familiars encountered who wanted to join your team (not necessarily joined)."
FISH_STAT_TOOLTIP = "Total number of fish caught."

ON_OFF_TOOLTIP = "Turn ON/OFF the autopilot. When ON, the autopilot will run continuously until stopped."
GITHUB_TOOLTIP = "Visit the GitHub page to report bugs or view the source code."
DISCORD_TOOLTIP = "Join the Discord server to join the community."
WIKI_TOOLTIP = "Visit the Wiki page for more information about the game and its mechanics."

LOGGER_TOOLTIP = "View the log of actions performed by the autopilot"
GAME_PATH_TOOLTIP = "Select the game path to automatically open the game when the application starts."

ENABLE_SWITCH_TOOLTIP = "Enable or disable the selected automation using this switch."
ALWAYS_ON_TOP_TOOLTIP = "Keep the application window always on top of other windows."
DIFFICULTY_TOOLTIP = "Select the difficulty level for the zone selected."